const SB='https://xkykassfemobpwvuojie.supabase.co';
const H=()=>({apikey:process.env.SUPABASE_SERVICE_ROLE_KEY,Authorization:`Bearer ${process.env.SUPABASE_SERVICE_ROLE_KEY}`,'Content-Type':'application/json',Prefer:'return=representation'});
const norm=s=>(s||'').trim().replace(/[أإآ]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه').toLowerCase();
const aliases={الابناء:'الأولاد',ابناء:'الأولاد',اولاد:'الأولاد',الاولاد:'الأولاد',ولاد:'الأولاد',كاش:'نقدي',cash:'نقدي',palpay:'PalPay','بال باي':'PalPay','بل باي':'PalPay'};
const canon=s=>aliases[norm(s)]||s?.trim()||null;
async function q(path,opt={}){const r=await fetch(`${SB}/rest/v1/${path}`,{...opt,headers:{...H(),...(opt.headers||{})}});const text=await r.text();if(!r.ok)throw new Error(text);return text?JSON.parse(text):null}
async function accounts(){return q('accounts?select=id,name,current_balance,is_active&is_active=eq.true')}
async function accountByName(name){const a=await accounts(),n=norm(canon(name));return a.find(x=>norm(x.name)===n||norm(x.name).includes(n)||n.includes(norm(x.name)))}
async function balances(){const a=await accounts();let cash=0,palpay=0;for(const x of a){if(norm(x.name).includes('نقد'))cash=+x.current_balance||0;if(norm(x.name).includes('palpay')||norm(x.name).includes('بال باي'))palpay=+x.current_balance||0}return{cash,palpay,accounts:a}}
async function ensureCategory(main,sub,kind='expense'){
 main=canon(main)||'أخرى'; sub=canon(sub);
 let roots=await q(`categories?select=*&parent_id=is.null&kind=eq.${kind}`);let root=roots.find(x=>norm(x.name)===norm(main));
 if(!root){[root]=await q('categories',{method:'POST',body:JSON.stringify({name:main,kind})})}
 if(!sub)return root;
 let kids=await q(`categories?select=*&parent_id=eq.${root.id}`);let kid=kids.find(x=>norm(x.name)===norm(sub));
 if(!kid){[kid]=await q('categories',{method:'POST',body:JSON.stringify({name:sub,parent_id:root.id,kind})})}return kid;
}
async function addTx(b){const type=b.transaction_type||'expense';const acc=await accountByName(b.account||b.payment_method);if(!acc)throw new Error('الحساب غير معروف. استخدم نقدي أو PalPay.');const main=canon(b.main_category)||'أخرى',sub=canon(b.sub_category);const cat=await ensureCategory(main,sub,type==='income'?'income':'expense');const amount=Number(b.amount);if(!(amount>0))throw new Error('المبلغ غير صحيح');const row={transaction_type:type,amount,currency:'ILS',account_id:acc.id,category_id:cat?.id||null,main_category:main,sub_category:sub,merchant:b.merchant||null,payment_method:canon(b.payment_method||b.account),description:b.description||null,transaction_date:b.transaction_date||new Date().toISOString(),original_text:b.original_text||null,source:'voice-ai',ai_confidence:b.ai_confidence??1};let [tx]=await q('transactions',{method:'POST',body:JSON.stringify(row)});const delta=type==='income'?amount:-amount;await q(`accounts?id=eq.${acc.id}`,{method:'PATCH',body:JSON.stringify({current_balance:(+acc.current_balance||0)+delta,updated_at:new Date().toISOString()})});return tx}
async function recent(limit=10){return q(`transactions?select=*&order=transaction_date.desc&limit=${Math.min(Number(limit)||10,50)}`)}
async function updateTx(b){let tx;if(b.id){[tx]=await q(`transactions?select=*&id=eq.${b.id}`)}else{[tx]=await recent(1)}if(!tx)throw new Error('لم أجد العملية');const oldAcc=tx.account_id?(await q(`accounts?select=*&id=eq.${tx.account_id}`))[0]:null;if(oldAcc){const rev=tx.transaction_type==='income'?-(+tx.amount):(+tx.amount);await q(`accounts?id=eq.${oldAcc.id}`,{method:'PATCH',body:JSON.stringify({current_balance:(+oldAcc.current_balance||0)+rev})})}const patch={};for(const k of ['amount','merchant','description','transaction_date','main_category','sub_category'])if(b[k]!=null)patch[k]=k.includes('category')?canon(b[k]):b[k];let newAcc=oldAcc;if(b.account||b.payment_method){newAcc=await accountByName(b.account||b.payment_method);if(!newAcc)throw new Error('الحساب غير معروف');patch.account_id=newAcc.id;patch.payment_method=canon(b.payment_method||b.account)}patch.updated_at=new Date().toISOString();let [updated]=await q(`transactions?id=eq.${tx.id}`,{method:'PATCH',body:JSON.stringify(patch)});const amt=Number(updated.amount);if(newAcc){const delta=updated.transaction_type==='income'?amt:-amt;await q(`accounts?id=eq.${newAcc.id}`,{method:'PATCH',body:JSON.stringify({current_balance:(+newAcc.current_balance||0)+delta})})}return updated}
async function deleteTx(b){let tx;if(b.id){[tx]=await q(`transactions?select=*&id=eq.${b.id}`)}else{[tx]=await recent(1)}if(!tx)throw new Error('لم أجد العملية');if(tx.account_id){const [acc]=await q(`accounts?select=*&id=eq.${tx.account_id}`);if(acc){const delta=tx.transaction_type==='income'?-(+tx.amount):(+tx.amount);await q(`accounts?id=eq.${acc.id}`,{method:'PATCH',body:JSON.stringify({current_balance:(+acc.current_balance||0)+delta})})}}await q(`transactions?id=eq.${tx.id}`,{method:'DELETE'});return{deleted:true,transaction:tx}}
async function summary(days=30){const since=new Date(Date.now()-Number(days)*86400000).toISOString();const rows=await q(`transactions?select=amount,transaction_type,main_category,sub_category,merchant,transaction_date&transaction_date=gte.${encodeURIComponent(since)}`);const out={expense:0,income:0,by_category:{},count:rows.length};for(const x of rows){if(x.transaction_type==='expense'){out.expense+=+x.amount;out.by_category[x.main_category||'أخرى']=(out.by_category[x.main_category||'أخرى']||0)+(+x.amount)}else if(x.transaction_type==='income')out.income+=+x.amount}return out}
export default async function handler(req,res){if(!process.env.SUPABASE_SERVICE_ROLE_KEY)return res.status(500).json({error:'SUPABASE_SERVICE_ROLE_KEY missing'});try{if(req.method==='GET'){const a=req.query.action;if(a==='balances')return res.json(await balances());if(a==='recent')return res.json(await recent(req.query.limit));if(a==='summary')return res.json(await summary(req.query.days));return res.status(400).json({error:'unknown action'})}if(req.method==='POST'){const {action,...body}=req.body||{};let data;if(action==='add_transaction')data=await addTx(body);else if(action==='update_transaction')data=await updateTx(body);else if(action==='delete_transaction')data=await deleteTx(body);else if(action==='create_category')data=await ensureCategory(body.main_category,body.sub_category,body.kind);else if(action==='balances')data=await balances();else if(action==='recent')data=await recent(body.limit);else if(action==='summary')data=await summary(body.days);else return res.status(400).json({error:'unknown action'});return res.json({ok:true,data})}return res.status(405).json({error:'Method not allowed'})}catch(e){return res.status(500).json({error:String(e.message||e)})}}
